branch for merge
masbys/hh-school-2020-hw-java-collections-stream pull request #1
Opened 2020-12-07 15:31 UTC by masbys

Выполненное дз по java-collections-stream

2020-12-08 15:28 UTC, genroelgvozo requested changes

2020-12-08 15:28 UTC, genroelgvozo commented on src/main/java/tasks/Task1.java
> +        Map<Integer, Person> personMap = persons.stream()
вопросов нет

2020-12-08 15:28 UTC, genroelgvozo commented on src/main/java/tasks/Task2.java
> +        return Stream.concat(persons1.stream(), persons2.stream())
Все гуд

2020-12-08 15:28 UTC, genroelgvozo commented on src/main/java/tasks/Task3.java
> +        return persons.stream()
Все гуд

2020-12-08 15:28 UTC, genroelgvozo commented on src/main/java/tasks/Task4.java
> +        return persons.stream()
Все ок)

2020-12-08 15:28 UTC, genroelgvozo commented on src/main/java/tasks/Task5.java
> +        return personList;
а тут чего вдруг не через стримы?) ты же можешь бежать по персонам, и так же в лямбде просто брать айди у персоны и вынимать из мапы арейку, заранее подготавливать не нужно

2020-12-08 15:28 UTC, genroelgvozo commented on src/main/java/tasks/Task6.java
> +        return personAreaSet;
по скорости все ок) Если хочешь попробуй просто на стримы переписать, как минимум превращение в мапу просто, ну и два цикла тоже можно через flatMap

2020-12-08 15:28 UTC, genroelgvozo commented on src/main/java/tasks/Task7.java
> +    }
ну тут точно попробуй стримы, намного кратче и понятнее

2020-12-08 15:28 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +    //оставляем проверку, т.к. skip для пусого листа - NullPointerException
твоя проверка тоже NullPointerException =) 
ты наверняка проверила для null а не пустого листа (а тут все таки предполагает. А в случае пустого листа скип работает, поэтому проверку можно убрать

2020-12-08 15:28 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +    //оставляем проверку, т.к. skip для пусого листа - NullPointerException
Еще вопрос чем плох ремув принципиально (кроме скорости!)

2020-12-08 15:28 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +        return new HashSet<>(getNames(persons));
тут ок

2020-12-08 15:28 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +    public String convertPersonToString(Person person) {
тут тоже ок)

2020-12-08 15:28 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +    public Map<Integer, String> getPersonNames(Collection<Person> persons) {
а тут почему бы лаконичный коллект через стримы не использовать?)

2020-12-08 15:28 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +        return allPersonSet.size() < person1Set.size() + person2Set.size();
работать будет, и даже быстро, но есть чуток лаконичнее способ, и только с одним сетом)
stream().anyMatch
или Collections.disjoint

2020-12-08 15:28 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +        return numbers.filter(num -> num % 2 == 0).count();
чем плох изначальный код?

2020-12-11 06:52 UTC, masbys commented on src/main/java/tasks/Task8.java
> +    //оставляем проверку, т.к. skip для пусого листа - NullPointerException
> Еще вопрос чем плох ремув принципиально (кроме скорости!)

При ремув мы изменим лист, удалив первую персону, а она может нам еще когда-то пригодиться.

2020-12-11 07:43 UTC, merged

2020-12-11 07:44 UTC, masbys commented on src/main/java/tasks/Task5.java
> +        return personList;
> а тут чего вдруг не через стримы?) ты же можешь бежать по персонам, и так же в лямбде просто брать айди у персоны и вынимать из мапы арейку, заранее подготавливать не нужно

сделала через стримы

2020-12-11 07:50 UTC, masbys commented on src/main/java/tasks/Task8.java
> +        return numbers.filter(num -> num % 2 == 0).count();
> чем плох изначальный код?

т.к.  count это поле, у него нет get/set, не понятно зачем оно нужно

2020-12-11 07:51 UTC, masbys commented on src/main/java/tasks/Task6.java
> +        return personAreaSet;
> по скорости все ок) Если хочешь попробуй просто на стримы переписать, как минимум превращение в мапу просто, ну и два цикла тоже можно через flatMap

мапу через стримы сделала, а вот циклы не очень получилось, т.к. не поняла как  с помощью flatMap просто передать person

2020-12-11 07:52 UTC, masbys commented on src/main/java/tasks/Task7.java
> +    }
> ну тут точно попробуй стримы, намного кратче и понятнее

сделала

2020-12-11 07:58 UTC, masbys commented on src/main/java/tasks/Task8.java
> +    public Map<Integer, String> getPersonNames(Collection<Person> persons) {
> а тут почему бы лаконичный коллект через стримы не использовать?)

сделала

2020-12-11 07:58 UTC, masbys commented on src/main/java/tasks/Task8.java
> +        return allPersonSet.size() < person1Set.size() + person2Set.size();
> работать будет, и даже быстро, но есть чуток лаконичнее способ, и только с одним сетом)
> stream().anyMatch
> или Collections.disjoint

выполнила через disjoint